name: cz.vutbr.fit.cphoto.deit-vis-loc
channels:
  - defaults
  - pytorch
dependencies:
  - cudatoolkit=11.0
  - pip
  - python=3.6
  - pytorch==1.7.1
  - torchvision==0.8.2
  - pip:
    - timm==0.3.2
    - safe-gpu==1.3

